<?php
/**
 * modules/committee_reports/export_pdf.php
 * ------------------------------------------------------------------
 * Exports the selected report type (Committee/Workload/Performance)
 * as a downloadable PDF using the app's existing SimplePdf class
 * (same helper modules/issues/export_pdf.php uses).
 * ------------------------------------------------------------------
 */

require_once __DIR__ . '/../../includes/auth.php';
require_once __DIR__ . '/../../includes/SimplePdf.php';
require_once __DIR__ . '/report_data.php';
require_once __DIR__ . '/report_narrative.php';
requireRole([ROLE_ADMIN, ROLE_STAFF]);

$pdo = db();
$type = in_array($_GET['type'] ?? '', ['committee', 'workload', 'performance'], true) ? $_GET['type'] : 'committee';
$committeeId = (int)($_GET['committee_id'] ?? 0);
$dateFrom = clean($_GET['date_from'] ?? '');
$dateTo = clean($_GET['date_to'] ?? '');
$dateFrom = preg_match('/^\d{4}-\d{2}-\d{2}$/', $dateFrom) ? $dateFrom : null;
$dateTo = preg_match('/^\d{4}-\d{2}-\d{2}$/', $dateTo) ? $dateTo : null;

$labels = ['committee' => 'Committee Report', 'workload' => 'Workload Report', 'performance' => 'Performance Report'];
$title = $labels[$type];

$data = buildCommitteeReportData($pdo, $type, $committeeId, $dateFrom, $dateTo);
$narrative = buildReportNarrative($pdo, $type, $data, $committeeId);
$committeeName = 'All Committees';
if ($committeeId > 0) {
    $committeeStmt = $pdo->prepare('SELECT committee_name FROM committees WHERE committee_id = :id');
    $committeeStmt->execute([':id' => $committeeId]);
    $committeeName = (string)($committeeStmt->fetchColumn() ?: 'Selected Committee');
}

$pdf = new SimplePdf('CITY COUNCIL OF MANILA  |  ' . strtoupper($title), 'Generated ' . date('F j, Y g:i A') . '  |  Draft for review');
$pdf->setFooter($title . ' | Generated by CMAS');
$pdf->addLine('REPUBLIC OF THE PHILIPPINES', 10, true);
$pdf->addLine('CITY OF MANILA', 10, true);
$pdf->addLine('CITY COUNCIL OF MANILA', 11, true);
$pdf->addSpacer(6);
$pdf->addLine(strtoupper($title), 13, true);
$pdf->addLine('Committee: ' . $committeeName . ' | Prepared by: ' . (currentUser()['full_name'] ?? 'CMAS User'), 9);
if ($type === 'performance') $pdf->addLine('Reporting period: ' . ($dateFrom ?? 'Beginning') . ' to ' . ($dateTo ?? 'Current'), 9);
$pdf->addSpacer(6);
$pdf->addLine('EXECUTIVE SUMMARY', 10, true);
$pdf->addLine($narrative['executive_summary'] ?? 'Insufficient data available for this section.', 9);
$pdf->addLine($type === 'committee' ? 'FINDINGS / OBSERVATIONS' : ($type === 'workload' ? 'WORKLOAD ANALYSIS' : 'PERFORMANCE ANALYSIS'), 10, true);
$pdf->addLine($narrative['analysis'] ?? 'Insufficient data available for this section.', 9);
$pdf->addLine('OBSERVATIONS', 10, true);
$pdf->addLine($narrative['observations'] ?? 'Insufficient data available for this section.', 9);
$pdf->addLine('RECOMMENDATIONS', 10, true);
$pdf->addLine($narrative['recommendations'] ?? 'Insufficient data available for this section.', 9);
$pdf->addLine('CONCLUSION', 10, true);
$pdf->addLine($narrative['conclusion'] ?? 'Insufficient data available for this section.', 9);
$pdf->addLine('SUPPORTING DATA', 10, true);

$colWidths = match ($type) {
    'workload'    => [110, 90, 90, 55, 45, 65, 60],
    'performance' => [115, 75, 55, 55, 60, 55, 75, 75],
    default       => [130, 110, 60, 70, 90],
};

$tableHeaders = $data['export_headers'] ?? $data['headers'];
$tableRows = $data['export_rows'] ?? $data['rows'];
if (empty($tableRows)) $tableRows[] = array_fill(0, count($tableHeaders), '');

$pdf->addTable($tableHeaders, $colWidths, $tableRows);

logActivity(currentUserId(), 'Export', 'Exported ' . $title . ' PDF' . ($committeeId ? ' (committee #' . $committeeId . ')' : ' (all committees)'));

$filename = 'committee-' . $type . '-report-' . date('Ymd-His') . '.pdf';

$pdo->prepare(
    'INSERT INTO committee_reports (committee_id, generated_by, report_title, report_type, file_path, generated_at)
     VALUES (:cid, :by, :title, :type, :path, NOW())'
)->execute([
    ':cid' => $committeeId ?: null, ':by' => currentUserId(), ':title' => $title,
    ':type' => ucfirst($type), ':path' => $filename,
]);

$pdf->output($filename);
