<?php
/**
 * modules/committee_reports/index.php
 * ------------------------------------------------------------------
 * Committee Reporting module (Module 6). Lets Admin/Staff preview and
 * export three report types - Committee, Workload, and Performance -
 * as PDF, Excel, or a print-friendly page, and keeps a log of every
 * export in `committee_reports` for audit purposes.
 * ------------------------------------------------------------------
 */

require_once __DIR__ . '/../../includes/auth.php';
require_once __DIR__ . '/report_data.php';
requireRole([ROLE_ADMIN, ROLE_STAFF]);

$pageTitle  = 'Committee Reports';
$activeMenu = 'committee_reports';
$pdo = db();

$type = in_array($_GET['type'] ?? '', ['committee', 'workload', 'performance'], true) ? $_GET['type'] : 'committee';
$committeeId = (int)($_GET['committee_id'] ?? 0);

$committees = $pdo->query("SELECT committee_id, committee_name FROM committees ORDER BY committee_name")->fetchAll();
$reportData = buildCommitteeReportData($pdo, $type, $committeeId);

$recentReports = $pdo->query(
    "SELECT cr.*, u.full_name AS generated_by_name
     FROM committee_reports cr
     LEFT JOIN users u ON u.id = cr.generated_by
     ORDER BY cr.generated_at DESC LIMIT 10"
)->fetchAll();

$reportLabels = ['committee' => 'Committee Report', 'workload' => 'Workload Report', 'performance' => 'Performance Report'];

include __DIR__ . '/../../layouts/header.php';
?>
<div class="app-wrapper">
  <?php include __DIR__ . '/../../layouts/sidebar.php'; ?>

  <div class="main-content">
  <?php include __DIR__ . '/../../layouts/content-topbar.php'; ?>
  <div class="breadcrumb-bar d-flex justify-content-between align-items-center flex-wrap gap-2">
    <div>
      <h5 class="mb-0"><i class="bi bi-file-earmark-text text-primary"></i> Committee Reporting</h5>
      <small class="text-muted">Generate and export Committee, Workload, and Performance reports.</small>
    </div>
    <div class="d-flex gap-2 no-print">
      <a class="btn btn-outline-secondary btn-sm" target="_blank"
         href="print.php?type=<?= e($type) ?>&committee_id=<?= (int)$committeeId ?>">
        <i class="bi bi-printer"></i> Print
      </a>
      <a class="btn btn-outline-secondary btn-sm"
         href="export_pdf.php?type=<?= e($type) ?>&committee_id=<?= (int)$committeeId ?>">
        <i class="bi bi-file-earmark-pdf"></i> Export PDF
      </a>
      <a class="btn btn-outline-secondary btn-sm"
         href="export_excel.php?type=<?= e($type) ?>&committee_id=<?= (int)$committeeId ?>">
        <i class="bi bi-file-earmark-excel"></i> Export Excel
      </a>
    </div>
  </div>

  <div class="card mb-3">
    <div class="card-body py-3">
      <form method="get" class="row g-2 align-items-center">
        <div class="col-md-4">
          <label class="form-label small mb-1">Report Type</label>
          <select name="type" class="form-select form-select-sm" onchange="this.form.submit()">
            <?php foreach ($reportLabels as $val => $label): ?>
              <option value="<?= e($val) ?>" <?= $type === $val ? 'selected' : '' ?>><?= e($label) ?></option>
            <?php endforeach; ?>
          </select>
        </div>
        <div class="col-md-4">
          <label class="form-label small mb-1">Committee</label>
          <select name="committee_id" class="form-select form-select-sm" onchange="this.form.submit()">
            <option value="0">All Committees</option>
            <?php foreach ($committees as $c): ?>
              <option value="<?= (int)$c['committee_id'] ?>" <?= $committeeId === (int)$c['committee_id'] ? 'selected' : '' ?>>
                <?= e($c['committee_name']) ?>
              </option>
            <?php endforeach; ?>
          </select>
        </div>
      </form>
    </div>
  </div>

  <div class="card mb-3">
    <div class="card-header"><?= e($reportLabels[$type]) ?> Preview</div>
    <div class="table-responsive">
      <table class="table table-sm table-hover align-middle mb-0">
        <thead><tr><?php foreach ($reportData['headers'] as $h): ?><th><?= e($h) ?></th><?php endforeach; ?></tr></thead>
        <tbody>
          <?php if (empty($reportData['rows'])): ?>
            <tr><td colspan="<?= count($reportData['headers']) ?>" class="text-center text-muted py-4">No data available for this report yet.</td></tr>
          <?php else: foreach ($reportData['rows'] as $row): ?>
            <tr><?php foreach ($row as $cell): ?><td><?= e((string)$cell) ?></td><?php endforeach; ?></tr>
          <?php endforeach; endif; ?>
        </tbody>
      </table>
    </div>
  </div>

  <div class="card">
    <div class="card-header">Recently Generated Reports</div>
    <div class="table-responsive">
      <table class="table table-sm align-middle mb-0">
        <thead><tr><th>Title</th><th>Type</th><th>Generated By</th><th>Date</th></tr></thead>
        <tbody>
          <?php if (empty($recentReports)): ?>
            <tr><td colspan="4" class="text-center text-muted py-4">No reports generated yet.</td></tr>
          <?php else: foreach ($recentReports as $r): ?>
            <tr>
              <td><?= e($r['report_title']) ?></td>
              <td><span class="badge bg-light text-dark border"><?= e($r['report_type']) ?></span></td>
              <td><?= e($r['generated_by_name'] ?? 'Unknown') ?></td>
              <td><?= formatDateTime($r['generated_at']) ?></td>
            </tr>
          <?php endforeach; endif; ?>
        </tbody>
      </table>
    </div>
  </div>

<?php
include __DIR__ . '/../../layouts/footer.php';
?>
